'use client'
import { usePathname } from 'next/navigation'

import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const pathname = usePathname()

  return (
    <html lang="en" className='m-6'>
      <body className={inter.className}>
        <nav>
          <ul className='flex gap-6'>
            <li>
              <Link className={`link ${pathname === '/' ? 'active' : ''}`} href="/">
                Home
              </Link>
            </li>
             <li>
              <Link
                className={`link ${pathname === '/about' ? 'active' : ''}`}
                href="/about"
              >
                About
              </Link>
            </li>
             <li>
              <Link
                className={`link ${pathname === '/blogs' ? 'active' : ''}`}
                href="/blogs"
              >
                Blog
              </Link>
            </li>
            
          </ul>
          <hr />
        </nav>
        {children}
      </body>
    </html>
  )
}
